### ISSUE TITLE
mod conflicts with origin classes

### ISSUE THREAD

**Issue by Gamer-of-life** [tvanprooyen/mbm#18]
if I have origin classes in the mods folder with this mod then minecraft just wont launch

**Comment by Mysticpasta1** [comment]
[latest.log](https://github.com/tvanprooyen/mbm/files/6550019/latest.log)

**Comment by Mysticpasta1** [comment]
it is a mixin conflict with AxeItemMixin

**Comment by tvanprooyen** [comment]
Makes sense to me, I have a couple of older mixins that need to updated to inject the code rather than take over the class. I'll mark this as a bug and have it fixed for the next update.

**Comment by tvanprooyen** [comment]
Updated AxeItemMixin to work with origins. Tested it compatibility and origins now loads with MBM.

**Comment by Mysticpasta1** [comment]
yay, will it be released to CF soon

**Comment by Mysticpasta1** [comment]
hello will the fix be uploaded to CurseForge any time soon

**Comment by tvanprooyen** [comment]
It will be once 1.17 is released, so in the next couple of days

**Comment by Mysticpasta1** [comment]
so will it be a 1.16.5 file or a 1.17 file because the conflict is only on 1.16.5 right now afaik

**Comment by tvanprooyen** [comment]
There are other bugs and features that I'm working on as well. I have to make sure I'm doing more than one thing in a release. Unless its a major bug that affects the mod it self. Otherwise I would be releasing a new file way to much. Most people look for updates on mods when a major Minecraft release. That is why it gets released on the same day or a little after. Most times I don't really worry about old versions of minecraft, but I'll release a 1.16.5 version at the same time as the 1.17 due to the popularity of Origins. This issue will close when the mod is released as a type of notification.

**Comment by Mysticpasta1** [comment]
ok then :D

**Comment by tvanprooyen** [comment]
Updating to 1.17 is going to take a longer than initially planed.

**Comment by Mysticpasta1** [comment]
ah that is fine :D

**Comment by tvanprooyen** [comment]
1.16.5 version uploaded. It is now available on Curse Forge.

**Comment by Mysticpasta1** [comment]
:D yay thank you
